apiVersion: apps/v1
kind: Deployment
metadata:
  name: kdoom-deployment
  labels:
    app: kdoom
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: kdoom
  template:
    metadata:
      labels:
        app: kdoom
    spec:
      containers:
      - name: kdoom
        image: storaxdev/kubedoom:0.5.0
        ports:
        - containerPort: 5900
          protocol: TCP
      hostNetwork: True
      serviceAccountName: kubedoom
